export const kDi = Symbol('di.di')
export const kEmitter = Symbol('di.emitter')
export const kBooting = Symbol('di.booting')
export const kInConfigure = Symbol('di.inConfigure')
export const kPlugins = Symbol('di.plugins')